openapi: 3.0.0
info:
  title: uci
  version: 1.0.0
servers:
  - url: http://localhost:8085
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /api/v1/usedCars/5:
    put:
      tags:
        - default
      summary: http://localhost:8085/api/v1/usedCars/5
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                carId: 5
                vehicleType: hatchback
                model: zxi
                company: hyundaib
                price: 500000
                carName: i10
                bhp: 1200
                engineCapacity: 1200cc
                mileage: 12
                kmRun: 1000
                transmission: manual
                color: white
                seater: 5
                location: Doddanekundi
                version: petro
                owner: efg
                carStatus: Sold Out
                dateTime: '2021-11-03T06:28:35.315+00:00'
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/usedCars:
    post:
      tags:
        - default
      summary: http://localhost:8085/api/v1/usedCars
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                carId: 6
                vehicleType: sedan
                model: zxi
                company: mercedes
                price: 5000000
                carName: benz
                bhp: 2400
                engineCapacity: 2400cc
                mileage: 12
                kmRun: 1000
                transmission: manual
                color: white
                seater: 5
                location: Doddanekundi
                version: petrol
                owner: efg
                carStatus: Sold Out
                dateTime: '2021-11-03T06:28:35.315+00:00'
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: http://localhost:8085/api/v1/usedCars
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/usedCars/3:
    get:
      tags:
        - default
      summary: http://localhost:8085/api/v1/usedCars/3
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
